site_name: Notlarım
site_description: Yazılım, veri bilimi, yapay zeka ve siber güvenlik üzerine kişisel dokümantasyon
site_author: Berat Ölmez
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark mode
      primary: indigo
      accent: deep orange

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light mode
      primary: blue
      accent: deep orange
  font:
    text: Merriweather Sans
    code: Fira Code

  logo: /assets/logo.jpeg
  favicon: /assets/logo.jpeg
  features:
    - navigation.expand
    - navigation.sections
    - navigation.footer
    - search.highlight
    - content.code.copy
    - content.code.annotate
plugins:
  - search
  - tags
nav:
  - Ana Sayfa: 'index.md'
  - Yapay Zeka:
      - Yapay Zeka: ArtificialIntelligence/artificial_intelligence.md
      - Yapay Sinir Ağları:
          - Yapay Sinir Ağlarına Giriş: ArtificialIntelligence/ArtificialNeuralNetworks/artificial_neural_networks_introduction.md
          - TensorFlow: ArtificialIntelligence/ArtificialNeuralNetworks/tensorflow.md
      - Bulanık Mantık: ArtificialIntelligence/FuzzyLogic/introduction_to_fuzzy_logic.md
      - Pekiştirmeli Öğrenme: ArtificialIntelligence/ReinforcementLearning/reinforcement_learning.md
  - Veri Analizi:
      - Veri Madenciliği:
          - Giriş: DataAnalysis/DataMining/introduction_to_data_mining.md
          - Veri Ön İşleme: DataAnalysis/DataMining/preprocessing.md
          - Veri: DataAnalysis/DataMining/data.md
      - Veri Kümeleri Üzerine Çalışma: DataAnalysis/working_on_the_dataset.md
      - Matplotlib: DataAnalysis/matplotlib.md
      - Numpy: DataAnalysis/numpy.md
      - Pandas: DataAnalysis/pandas.md
  - Docker:
      - Ayberk Aytekin ile Hızlandırılmış Docker Eğitimi: Docker/accelerated_docker_training_ayti_tech.md
      - Gökhan Şengün ile Docker Compose: Docker/docker_compose_gokhan_sengun.md
      - Oracle Database ve SQLplus: Docker/oracle_database_sqlplus.md
      - Kullanışlı Komutlar: Docker/useful_commands.md
  - Etik Hacking:
      - Beyaz Hacker: EthicalHacking/beyaz_hacker.md
      - DNS Değişikliği: EthicalHacking/dns_change.md
      - Atıl Samancıoğlu ile Etik Hacking: EthicalHacking/ethical_hacking_atil_samancioglu.md
      - Vortex ile Harici Ağ: EthicalHacking/external_network_with_vortex.md
      - Ngrok: EthicalHacking/ngrok.md
      - Pro Manuel Web Sızma: EthicalHacking/pro_manuel_web_pentesting.md
      - Steganografi: EthicalHacking/steganografi.md
      - Wi-Fi Hacking: EthicalHacking/wifi_hacking.md
  - Git:
      - Git ve GitHub: Git/git_and_github.md
  - Bilgi Güvenliği & Kriptografi:
      - Giriş: InformationSecurity&Cryptography/introduction_to_information_security_and_cryptography.md
  - Staj:
      - Veri Tabanı Kurulumu: Intership/database_setup.md
      - Maven Komutları: Intership/mvn_commands.md
  - Java:
      - JavaFX:
          - JavaFX: Java/JavaFX/javafx.md
      - Java Spring:
          - Temel Anotasyonlar: Java/JavaSpring/basic_annotations.md
          - HTTP Metotları: Java/JavaSpring/http_methods.md
          - Spring Data JPA (Veri Tabanı İşlemleri): Java/JavaSpring/spring_data_jpa.md
          - Spring Validation (Doğrulama): Java/JavaSpring/spring_validation.md
          - Relations (Entity İlişkileri): Java/JavaSpring/relations.md
          - application.properties (Veri Tabanı Ayarları): Java/JavaSpring/application_properties.md
          - Exception Handling (Hata Yakalama): Java/JavaSpring/exceptions.md
          - Scheduled (Planlama): Java/JavaSpring/scheduled.md
          - JUnit Testleri: Java/JavaSpring/junit.md
          - JWT (JSON Web Token): Java/JavaSpring/json_web_token.md
#  - KeNot:
 #     - Şiirsel Notlar: KeNot/siirsel_notlar.md
  - Linux:
      - Bash: Linux/bash.md
      - Linux Komutları: Linux/linux_user_commands.md
  - MkDocs:
      - MkDocs Notları: MkDocs/mkdocs_notlari.md
  - Mobil Programlama:
      - BTK Kotlin: MobileProgramming/btk_kotlin.md
  - Ağ:
      - Bilgisayar Ağları: Network/computer_networks.md
      - IP, Subnetting, NAT, PAT: Network/ip_subnetting_nat_pat.md
      - Kablosuz Ağlara Giriş: Network/wireless_networks_introduction.md
  - Programlanabilir Yapılar:
      - Programlanabilir Yapılar: ProgrammableStructures/programmable_structures.md
  - Python:
      - Django (Sadık Turan): Python/django_sadik_turan.md
      - Python: Python/python.md
  - SQL:
      - BTK Akademi SQL: SQL/btk_akademi_sql.md

markdown_extensions:
  - codehilite:
      guess_lang: false
  - admonition
  - toc:
      permalink: true
  - tables
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format 
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - admonition:
  - pymdownx.details:

extra:
  generator: true
  social:
    - icon: simple/youtube
      link: https://www.youtube.com/watch?v=xlABhbnNrfI

copyright: Copyright &copy; 2025 Berat Ölmez